// <auto-generated />
using System;
using AnomalyDetectionProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnomalyDetectionProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220415205845_asd")]
    partial class asd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnomalyDetectionProject.Models.Action", b =>
                {
                    b.Property<int>("ActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionID"), 1L, 1);

                    b.Property<DateTime?>("ActionDateTime")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("MCUID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("ActionID");

                    b.HasIndex("ClientId");

                    b.ToTable("Action", "dbo");
                });

            modelBuilder.Entity("AnomalyDetectionProject.Models.AdminModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad_Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Admin_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("AnomalyDetectionProject.Models.Camera", b =>
                {
                    b.Property<int>("CameraZoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CameraZoneID"), 1L, 1);

                    b.Property<string>("ZoneDescription")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("ZonePriority")
                        .HasColumnType("int");

                    b.HasKey("CameraZoneID");

                    b.ToTable("Camera", "dbo");
                });

            modelBuilder.Entity("AnomalyDetectionProject.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<int>("CameraZoneID")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("ClientId");

                    b.HasIndex("CameraZoneID");

                    b.ToTable("Client", "dbo");
                });

            modelBuilder.Entity("AnomalyDetectionProject.Models.PostedData", b =>
                {
                    b.Property<int>("PostedDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostedDataId"), 1L, 1);

                    b.Property<string>("ActionPriority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AnomalyDateTime")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CameraZoneID")
                        .HasColumnType("int");

                    b.Property<string>("CrimeScreenshot")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.HasKey("PostedDataId");

                    b.HasIndex("CameraZoneID");

                    b.ToTable("PostedData", "dbo");
                });

            modelBuilder.Entity("AnomalyDetectionProject.Models.Action", b =>
                {
                    b.HasOne("AnomalyDetectionProject.Models.Client", "client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("client");
                });

            modelBuilder.Entity("AnomalyDetectionProject.Models.Client", b =>
                {
                    b.HasOne("AnomalyDetectionProject.Models.Camera", "camera")
                        .WithMany()
                        .HasForeignKey("CameraZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("camera");
                });

            modelBuilder.Entity("AnomalyDetectionProject.Models.PostedData", b =>
                {
                    b.HasOne("AnomalyDetectionProject.Models.Camera", "camera")
                        .WithMany()
                        .HasForeignKey("CameraZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("camera");
                });
#pragma warning restore 612, 618
        }
    }
}
